New change for ec2

diff --git a/.github/workflows/vm-aws.yml b/.github/workflows/vm-aws.yml
--- a/.github/workflows/vm-aws.yml
+++ b/.github/workflows/vm-aws.yml
@@ -50,16 +50,11 @@ jobs:
             -var="altair_instance_type=${{ github.event.inputs.altair_instance_type }}" \
             -var="altair_instance_name=${{ github.event.inputs.altair_instance_name }}"
 
-      - name: Retrieve Terraform Outputs
-        run: |
-          cd vm-aws
-          terraform output -json > terraform_outputs.json
-
       - name: Extract Public IP and Private Key
         id: extract-vars
         run: |
-          PUBLIC_IP=$(jq -r '.altair_instance_public_ip.value' vm-aws/terraform_outputs.json || echo "ERROR")
-          PRIVATE_KEY=$(jq -r '.altair_private_key.value' vm-aws/terraform_outputs.json || echo "ERROR")
+          PUBLIC_IP=$(terraform output -raw altair_instance_public_ip || echo "ERROR")
+          PRIVATE_KEY=$(terraform output -raw altair_private_key || echo "ERROR")
           if [ "$PUBLIC_IP" = "ERROR" ] || [ -z "$PUBLIC_IP" ]; then
             echo "Failed to extract public IP. Exiting..."
             exit 1
@@ -68,8 +63,8 @@ jobs:
             echo "Failed to extract private key. Exiting..."
             exit 1
           fi
-          echo "public_ip=$PUBLIC_IP" >> $GITHUB_ENV
-          echo "private_key=$PRIVATE_KEY" >> $GITHUB_ENV
+          echo "::set-output name=public_ip::$PUBLIC_IP"
+          echo "::set-output name=private_key::$PRIVATE_KEY"
 
       - name: Send Email Notification
         uses: dawidd6/action-send-mail@v3
@@ -87,11 +82,11 @@ jobs:
             The AWS EC2 instance has been successfully created.
 
             Instance Details:
-            - Public IP: ${{ env.public_ip }}
+            - Public IP: ${{ steps.extract-vars.outputs.public_ip }}
             
             Private Key:
-            ${{ env.private_key }}
+            ${{ steps.extract-vars.outputs.private_key }}
             
             You can connect to the instance using the following command:
-            ssh -i "your-private-key.pem" ec2-user@${{ env.public_ip }}
+            ssh -i "your-private-key.pem" ec2-user@${{ steps.extract-vars.outputs.public_ip }}
 
